In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing " , arr[2:7])
print("with steps ",arr[1:8:2])
print("negative indexing" , arr[-3])


Basic Slicing  [3 4 5 6 7]
with steps  [2 4 6 8]
negative indexing 8


In [5]:
arr_2d = np.array([[1,2,3],
[4,5,6],
[7,8,9]])

print("specific element ",arr_2d[1,2])
print("entire row:", arr_2d[1])
print("entire col" , arr_2d[:,1])

specific element  6
entire row: [4 5 6]
entire col [2 5 8]


### Sorting

In [ ]:
unsorted = np.array([3,1,4,1,5,9,2,6])
print("Sorted Array", np.sort(unsorted))


arr_2d_unsorted = np.array([[3,2] , [1,2] , [3,9] ])
print("sorted 2d array by column ",np.sort(arr_2d_unsorted , axis = 0)) # row wise sort (axis = 0 column wise)

Sorted Array [1 1 2 3 4 5 6 9]
sorted 2d array by column  [[2 3]
 [1 2]
 [3 9]]


In [12]:
##Filter

numbers = np.array([1,5,3,13,5,6,7,17,9,10])
even_numbers = numbers[numbers % 2 == 0]
print("even numbers" , even_numbers)

even numbers [ 6 10]


### Filtering with mask

In [15]:
mask = numbers > 5
print("numbers greater than 5", numbers[mask])

numbers greater than 5 [13  6  7 17  9 10]


### fancy indexing vs np.where()

In [ ]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result) #store index based on condition
print("np where" , numbers[where_result])

arr = np.array([1,2,3,4,5])
# condition ? value_if_true , value_if_false
result = np.where(arr % 2 == 0 , 100 , 0) 
print(result)




[1 3 5]
(array([3, 5, 6, 7, 8, 9]),)
np where [13  6  7 17  9 10]
[  0 100   0 100   0]


### Adding and removing data

In [3]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combine = np.concatenate((arr1,arr2))
print(combine)

[1 2 3 4 5 6]


### Array compatiblilty

In [4]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatibilty shape" , a.shape == b.shape)


Compatibilty shape True


In [6]:
original = np.array([[1,2] , [3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original , new_row))
print(original)
print("new row added", with_new_row)


new_col = np.array([[7] , [8]])
with_new_col = np.hstack((original , new_col))
print("new col added", with_new_col)

[[1 2]
 [3 4]]
new row added [[1 2]
 [3 4]
 [5 6]]
new col added [[1 2 7]
 [3 4 8]]


In [8]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print("Array after deletion: ",deleted) ##index 2 ele deleted

Array after deletion:  [1 2 4 5]
