In [1]:
import numpy as np

In [2]:
py_list = [1,2,3] #concat
print("python list multiplication: ",py_list * 2)

np_array = np.array([1,2,3]) #multiply element wise
print("python array multiply: ",np_array * 2)

python list multiplication:  [1, 2, 3, 1, 2, 3]
python array multiply:  [2 4 6]


In [3]:
zeros = np.zeros((3,4))
print("zeros array: \n", zeros)

ones = np.ones((2,3))
print("ones array: \n",ones)

full = np.full((2,2) , 5)
print("full array: \n" , full)

random = np.random.random((2,3))
print("random array: \n" , random)

sequence = np.arange(0,10,3) #non inclusive (dont consider boundryb)
print("sequence array: \n",sequence)


zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[5 5]
 [5 5]]
random array: 
 [[0.72776131 0.19958338 0.765277  ]
 [0.52300262 0.0122508  0.90942215]]
sequence array: 
 [0 3 6 9]


### Vector , matrix and tensor

In [4]:
vector = np.array([1,2,3])
print("Vector: ",vector)

matrix = np.array([[1,2,3], 
                  [4,5,6]])
print("Matrix: ", matrix)

tensor = np.array([[[1,2] , [3,4]],
                   [[5,6] , [7,8]]]) #multidimensional array in multidimensional arr
print("tensor: ", tensor)



Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties


In [5]:
arr = np.array([[1,2,3], 
                  [4,5,6]]) 
print("Shape: ",arr.shape)
print("Shape: ",arr.ndim)
print("Shape: ",arr.size)
print("Shape: ",arr.dtype)



Shape:  (2, 3)
Shape:  2
Shape:  6
Shape:  int64


In [6]:
arr = np.arange(12)
print("original array ", arr)

reshaped = arr.reshape((3,4)) # make flatten arr into col n rows
print("\n Reshaped array ", reshaped)

flattened = reshaped.flatten() # flatten rows and cols
print("\n FLattened array: ", flattened)

array = np.array([[1,2,3], 
                  [4,5,6]]) 

#ravel (return view , instead of copy) both og and ravel point to same memory
raveled = reshaped.ravel()
print("\n raveled array ",raveled)

#transpose
transpose = reshaped.T
print("\n transpose array ", transpose)



original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 FLattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 transpose array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
